# Generated by Django 2.1.2 on 2019-03-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20190312_1012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='post',
            name='opid',
        ),
        migrations.RemoveField(
            model_name='post',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='password',
            field=models.CharField(default='', max_length=20),
        ),
    ]
