# Generated by Django 2.1.2 on 2019-03-12 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20190312_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='username',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='password',
            new_name='opid',
        ),
        migrations.AddField(
            model_name='post',
            name='phone',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='post',
            field=models.CharField(default='', max_length=30),
        ),
    ]
