# Generated by Django 2.1.2 on 2019-03-13 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20190312_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post',
            field=models.CharField(choices=[('a', 'a'), ('b', 'b'), ('c', 'c')], max_length=30),
        ),
    ]
